{% set name = "fastq_preprocessor" %}
{% set version = "2023.7.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jolespin/fastq_preprocessor/releases/download/v{{version}}/fastq_preprocessor-{{version}}.tar.gz

build:
  noarch: python
  script: $PYTHON -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - samtools >=1.9
    - seqkit
    - bbmap
    - fastp
    - bowtie2
    - pandas >=0.24.2
    - scandir
    - tqdm
    - bz2file
    - tzlocal
    - pathlib2
    - requests
    - numpy >=1.11
    - soothsayer_utils >=2022.6.24
    - genopype >=2023.5.15
    - coreutils

about:
  home: https://github.com/jolespin/fastq_preprocessor
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'A fastq preprocessor for short read sequencing'
  description: 'A fastq preprocessor for short read sequencing. Can be used as a wrapper around fastp for a standardized directory structure or can feed the trimmed reads into bowtie2 if an index is provided to decontaminate sequences similar to kneaddata (useful in metagenomics to remove host reads). Also includes functionality to filter based on k-mer profiles and is useful for quantifying the amount of ribosomal reads. At each stage, seqkit stats is run so there are read stats that can be used post hoc.'
