{% set name = "fastq_preprocessor" %}
{% set version = "2026.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jolespin/fastq_preprocessor/releases/download/v{{version}}/fastq_preprocessor-{{version}}.tar.gz

build:
  noarch: python
  script: $PYTHON -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - sh
    - loguru
    - pandas >=0.24
    - samtools >=1.9
    - seqkit
    - bbmap
    - fastp
    - bowtie2
    - minimap2
    - pigz
    - fastplong

about:
  home: https://github.com/jolespin/fastq_preprocessor
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A fastq preprocessor for short and long read sequencing'
  description: 'A fastq preprocessor for short and long read sequencing. Optional contamination removal'
